### PR TITLE
Adds js word list

### PR DESCRIPTION
**Pull request by rthbound**
From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Methods_Index

### CODE REVIEW

**Comment by jhass** [comment]
Mmh, I feel like this should be fully qualified names, like `Math.abs` etc.

**Comment by rthbound** [comment]
Ah, I'll have to find another source... sussing that out from this developer.mozilla.org resource wouldn't be easy.

**Comment by rthbound** [comment]
http://www.w3schools.com/jsref/jsref_obj_string.asp might be a good source (String, Number, Operators, etc).

A bit more work, but I agree that'd make a better word list.

**Comment by jhass** [comment]
Otoh http://www.w3fools.com/

**Comment by jhass** [comment]
Thanks

**Pull request merged**
